CREATE TABLE MEMBER
(
    MEMBER_ID    character varying(30) NOT NULL,
    MEMBER_PW    character varying(30) NOT NULL,
    MEMBER_NICK    character varying(20) NOT NULL,
    MEMBER_NAME    character varying(20) NOT NULL,
    MEMBER_PHON    integer NOT NULL,
    MEMBER_ADDR    character varying(100) NOT NULL,
    MEMBER_ADDR2    character varying(100) NOT NULL,
    MEMBER_ZIP    character varying(10) NOT NULL,
    MEMBER_SINCE    timestamp without time zone,
    MEMBER_UPDT    timestamp without time zone,
    MEMBER_CHECK    boolean NOT NULL,
    MEMBER_TYPE    character(1) NOT NULL
);

COMMENT ON COLUMN MEMBER.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN MEMBER.MEMBER_PW IS '비밀번호';

COMMENT ON COLUMN MEMBER.MEMBER_NICK IS '닉네임';

COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '이름';

COMMENT ON COLUMN MEMBER.MEMBER_PHON IS '폰번호';

COMMENT ON COLUMN MEMBER.MEMBER_ADDR IS '주소';

COMMENT ON COLUMN MEMBER.MEMBER_ADDR2 IS '상세주소';

COMMENT ON COLUMN MEMBER.MEMBER_ZIP IS '우편번호';

COMMENT ON COLUMN MEMBER.MEMBER_SINCE IS '가입일';

COMMENT ON COLUMN MEMBER.MEMBER_UPDT IS '수정일';

COMMENT ON COLUMN MEMBER.MEMBER_CHECK IS '메일수신여부';

COMMENT ON COLUMN MEMBER.MEMBER_TYPE IS '가입타입';

COMMENT ON TABLE MEMBER IS '회원';

CREATE UNIQUE INDEX MEMBER_PK ON MEMBER
( MEMBER_ID );

ALTER TABLE MEMBER
 ADD CONSTRAINT MEMBER_PK PRIMARY KEY 
 USING INDEX MEMBER_PK;

COMMENT ON COLUMN MEMBER.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN MEMBER.MEMBER_PW IS '비밀번호';

COMMENT ON COLUMN MEMBER.MEMBER_NICK IS '닉네임';

COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '이름';

COMMENT ON COLUMN MEMBER.MEMBER_PHON IS '폰번호';

COMMENT ON COLUMN MEMBER.MEMBER_ADDR IS '주소';

COMMENT ON COLUMN MEMBER.MEMBER_ADDR2 IS '상세주소';

COMMENT ON COLUMN MEMBER.MEMBER_ZIP IS '우편번호';

COMMENT ON COLUMN MEMBER.MEMBER_SINCE IS '가입일';

COMMENT ON COLUMN MEMBER.MEMBER_UPDT IS '수정일';

COMMENT ON COLUMN MEMBER.MEMBER_CHECK IS '메일수신여부';

COMMENT ON COLUMN MEMBER.MEMBER_TYPE IS '가입타입';

COMMENT ON TABLE MEMBER IS '회원';

CREATE TABLE POST_IMG
(
    POST_NO    integer NOT NULL,
    POST_IMG_NO    SERIAL not NULL,
    POST_IMG_IMG    character varying(200) NOT NULL,
    POST_IMG_SEQ    integer NOT NULL,
    POST_IMG_UUID    character varying(100) NOT NULL
);

COMMENT ON COLUMN POST_IMG.POST_NO IS '포스터번호';

COMMENT ON COLUMN POST_IMG.POST_IMG_NO IS '포스트이미지번호';

COMMENT ON COLUMN POST_IMG.POST_IMG_IMG IS '포스트이미지내용';

COMMENT ON COLUMN POST_IMG.POST_IMG_SEQ IS '포스트이미지순서';

COMMENT ON COLUMN POST_IMG.POST_IMG_UUID IS '포스트이미지중복방지';

COMMENT ON TABLE POST_IMG IS 'SNS포스터이미지';

CREATE UNIQUE INDEX POST_IMG_PK ON POST_IMG
( POST_NO,POST_IMG_NO );

ALTER TABLE POST_IMG
 ADD CONSTRAINT POST_IMG_PK PRIMARY KEY 
 USING INDEX POST_IMG_PK;

COMMENT ON COLUMN POST_IMG.POST_NO IS '포스터번호';

COMMENT ON COLUMN POST_IMG.POST_IMG_NO IS '포스트이미지번호';

COMMENT ON COLUMN POST_IMG.POST_IMG_IMG IS '포스트이미지내용';

COMMENT ON COLUMN POST_IMG.POST_IMG_SEQ IS '포스트이미지순서';

COMMENT ON COLUMN POST_IMG.POST_IMG_UUID IS '포스트이미지중복방지';

COMMENT ON TABLE POST_IMG IS 'SNS포스터이미지';


CREATE TABLE REV_COM
(
    REV_COM_NO    SERIAL not NULL,
    REV_COM_CON    character varying(500) NOT NULL,
    REV_COM_SEQ    integer NOT NULL,
    REV_COMCLASS    integer NOT NULL,
    REV_COM_GROUP    integer NOT NULL,
    REV_COM_DATE    timestamp without time zone NOT NULL,
    REVIEW_NO    integer NOT NULL
);

COMMENT ON COLUMN REV_COM.REV_COM_NO IS '후기댓글번호';

COMMENT ON COLUMN REV_COM.REV_COM_CON IS '후기댓글내용';

COMMENT ON COLUMN REV_COM.REV_COM_SEQ IS '후기댓글순서';

COMMENT ON COLUMN REV_COM.REV_COMCLASS IS '후기댓글계층';

COMMENT ON COLUMN REV_COM.REV_COM_GROUP IS '후기댓글그룹';

COMMENT ON COLUMN REV_COM.REV_COM_DATE IS '후기댓글작성일';

COMMENT ON COLUMN REV_COM.REVIEW_NO IS '후기번호';

COMMENT ON TABLE REV_COM IS '후기댓글';

CREATE UNIQUE INDEX REV_COM_PK ON REV_COM
( REVIEW_NO,REV_COM_NO );

ALTER TABLE REV_COM
 ADD CONSTRAINT REV_COM_PK PRIMARY KEY 
 USING INDEX REV_COM_PK;

COMMENT ON COLUMN REV_COM.REV_COM_NO IS '후기댓글번호';

COMMENT ON COLUMN REV_COM.REV_COM_CON IS '후기댓글내용';

COMMENT ON COLUMN REV_COM.REV_COM_SEQ IS '후기댓글순서';

COMMENT ON COLUMN REV_COM.REV_COMCLASS IS '후기댓글계층';

COMMENT ON COLUMN REV_COM.REV_COM_GROUP IS '후기댓글그룹';

COMMENT ON COLUMN REV_COM.REV_COM_DATE IS '후기댓글작성일';

COMMENT ON COLUMN REV_COM.REVIEW_NO IS '후기번호';

COMMENT ON TABLE REV_COM IS '후기댓글';


CREATE TABLE POST_TAG
(
    PRODUCT_NO    integer NOT NULL,
    POST_NO    integer NOT NULL,
    POST_TAG_NO    SERIAL not NULL,
    POST_TAG_CON    character varying(500)
);

COMMENT ON COLUMN POST_TAG.PRODUCT_NO IS '상품번호';

COMMENT ON COLUMN POST_TAG.POST_NO IS '포스터번호';

COMMENT ON COLUMN POST_TAG.POST_TAG_NO IS '포스트태그번호';

COMMENT ON COLUMN POST_TAG.POST_TAG_CON IS '포스트태그내용';

COMMENT ON TABLE POST_TAG IS '포스트태그';

CREATE UNIQUE INDEX POST_TAG_PK ON POST_TAG
( PRODUCT_NO,POST_NO,POST_TAG_NO );

ALTER TABLE POST_TAG
 ADD CONSTRAINT POST_TAG_PK PRIMARY KEY 
 USING INDEX POST_TAG_PK;

COMMENT ON COLUMN POST_TAG.PRODUCT_NO IS '상품번호';

COMMENT ON COLUMN POST_TAG.POST_NO IS '포스터번호';

COMMENT ON COLUMN POST_TAG.POST_TAG_NO IS '포스트태그번호';

COMMENT ON COLUMN POST_TAG.POST_TAG_CON IS '포스트태그내용';

COMMENT ON TABLE POST_TAG IS '포스트태그';


CREATE TABLE REVIEW
(
    MEMBER_ID    character varying(30) NOT NULL,
    REVIEW_NO    SERIAL not NULL,
    REVIEW_TITLE    character varying(50) NOT NULL,
    REVIEW_DATE    timestamp without time zone NOT NULL,
    REVIEW_CON    character varying(5000) NOT NULL,
    REVIEW_SECREET    boolean NOT NULL,
    REVIEW_TYPE    character(1) NOT NULL,
    PRODUCT_NO    integer NOT NULL,
    REVIEW_SEQ    integer NOT NULL,
    REVIEW_VIEWS    integer NOT NULL
);

COMMENT ON COLUMN REVIEW.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN REVIEW.REVIEW_NO IS '후기번호';

COMMENT ON COLUMN REVIEW.REVIEW_TITLE IS '후기제목';

COMMENT ON COLUMN REVIEW.REVIEW_DATE IS '후기작성일';

COMMENT ON COLUMN REVIEW.REVIEW_CON IS '후기내용';

COMMENT ON COLUMN REVIEW.REVIEW_SECREET IS '비밀글여부';

COMMENT ON COLUMN REVIEW.REVIEW_TYPE IS '후기타입';

COMMENT ON COLUMN REVIEW.PRODUCT_NO IS '상품번호';

COMMENT ON COLUMN REVIEW.REVIEW_SEQ IS '후기글 순서';

COMMENT ON COLUMN REVIEW.REVIEW_VIEWS IS '후기 조회수';

COMMENT ON TABLE REVIEW IS '후기게시판';

CREATE UNIQUE INDEX REVIEW_PK ON REVIEW
( REVIEW_NO );

ALTER TABLE REVIEW
 ADD CONSTRAINT REVIEW_PK PRIMARY KEY 
 USING INDEX REVIEW_PK;

COMMENT ON COLUMN REVIEW.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN REVIEW.REVIEW_NO IS '후기번호';

COMMENT ON COLUMN REVIEW.REVIEW_TITLE IS '후기제목';

COMMENT ON COLUMN REVIEW.REVIEW_DATE IS '후기작성일';

COMMENT ON COLUMN REVIEW.REVIEW_CON IS '후기내용';

COMMENT ON COLUMN REVIEW.REVIEW_SECREET IS '비밀글여부';

COMMENT ON COLUMN REVIEW.REVIEW_TYPE IS '후기타입';

COMMENT ON COLUMN REVIEW.PRODUCT_NO IS '상품번호';

COMMENT ON COLUMN REVIEW.REVIEW_SEQ IS '후기글 순서';

COMMENT ON COLUMN REVIEW.REVIEW_VIEWS IS '후기 조회수';

COMMENT ON TABLE REVIEW IS '후기게시판';


CREATE TABLE MEM_AUTH
(
    MEMBER_ID    character varying(30) NOT NULL,
    MEM_AUTH_AUTH    character varying(50) DEFAULT 'AUTH_MEM' NOT NULL,
    MEM_AUTH_KEY    character varying(50) NOT NULL
);

COMMENT ON COLUMN MEM_AUTH.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN MEM_AUTH.MEM_AUTH_AUTH IS '권한';

COMMENT ON COLUMN MEM_AUTH.MEM_AUTH_KEY IS '인증키';

COMMENT ON TABLE MEM_AUTH IS '권한';

CREATE UNIQUE INDEX MEM_AUTH_PK ON MEM_AUTH
( MEMBER_ID );

ALTER TABLE MEM_AUTH
 ADD CONSTRAINT MEM_AUTH_PK PRIMARY KEY 
 USING INDEX MEM_AUTH_PK;

COMMENT ON COLUMN MEM_AUTH.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN MEM_AUTH.MEM_AUTH_AUTH IS '권한';

COMMENT ON COLUMN MEM_AUTH.MEM_AUTH_KEY IS '인증키';

COMMENT ON TABLE MEM_AUTH IS '권한';


CREATE TABLE SCORE
(
    SCORE_BOOL    numeric(3) NOT NULL,
    REVIEW_NO    integer NOT NULL,
    MEMBER_ID    character varying(30) NOT NULL,
    SCORE_NO    SERIAL not NULL
);

COMMENT ON COLUMN SCORE.SCORE_BOOL IS '평점 여부';

COMMENT ON COLUMN SCORE.REVIEW_NO IS '후기번호';

COMMENT ON COLUMN SCORE.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN SCORE.SCORE_NO IS '평점번호';

COMMENT ON TABLE SCORE IS '평점';

CREATE UNIQUE INDEX SCORE_PK ON SCORE
( MEMBER_ID,SCORE_NO );

ALTER TABLE SCORE
 ADD CONSTRAINT SCORE_PK PRIMARY KEY 
 USING INDEX SCORE_PK;

COMMENT ON COLUMN SCORE.SCORE_BOOL IS '평점 여부';

COMMENT ON COLUMN SCORE.REVIEW_NO IS '후기번호';

COMMENT ON COLUMN SCORE.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN SCORE.SCORE_NO IS '평점번호';

COMMENT ON TABLE SCORE IS '평점';


CREATE TABLE PROFILE
(
    MEMBER_ID    character varying(30) NOT NULL,
    PROFILE_NO    SERIAL not NULL,
    PROFILE_IMG    character varying(200) DEFAULT 'default.jpg' NOT NULL,
    PROFILE_UUID    character varying(100) NOT NULL,
    PROFILE_TYPE    character(1) NOT NULL,
    PROFILE_DATE    timestamp without time zone NOT NULL
);

COMMENT ON COLUMN PROFILE.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN PROFILE.PROFILE_NO IS '프로필 번호';

COMMENT ON COLUMN PROFILE.PROFILE_IMG IS '프로필사진';

COMMENT ON COLUMN PROFILE.PROFILE_UUID IS '프로필중복방지';

COMMENT ON COLUMN PROFILE.PROFILE_TYPE IS '이미지타입';

COMMENT ON COLUMN PROFILE.PROFILE_DATE IS '프로필등록일';

COMMENT ON TABLE PROFILE IS '프로필 이미지';

CREATE UNIQUE INDEX PROFILE_PK ON PROFILE
( MEMBER_ID,PROFILE_NO );

ALTER TABLE PROFILE
 ADD CONSTRAINT PROFILE_PK PRIMARY KEY 
 USING INDEX PROFILE_PK;

COMMENT ON COLUMN PROFILE.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN PROFILE.PROFILE_NO IS '프로필 번호';

COMMENT ON COLUMN PROFILE.PROFILE_IMG IS '프로필사진';

COMMENT ON COLUMN PROFILE.PROFILE_UUID IS '프로필중복방지';

COMMENT ON COLUMN PROFILE.PROFILE_TYPE IS '이미지타입';

COMMENT ON COLUMN PROFILE.PROFILE_DATE IS '프로필등록일';

COMMENT ON TABLE PROFILE IS '프로필 이미지';


CREATE TABLE TAG
(
    POST_NO    integer NOT NULL,
    TAG_NO    SERIAL not NULL,
    TAG_CONTENT    character varying(500) NOT NULL
);

COMMENT ON COLUMN TAG.POST_NO IS '포스터번호';

COMMENT ON COLUMN TAG.TAG_NO IS '태그번호';

COMMENT ON COLUMN TAG.TAG_CONTENT IS '태그내용';

COMMENT ON TABLE TAG IS '태그';

CREATE UNIQUE INDEX TAG_PK ON TAG
( POST_NO,TAG_NO );

ALTER TABLE TAG
 ADD CONSTRAINT TAG_PK PRIMARY KEY 
 USING INDEX TAG_PK;

COMMENT ON COLUMN TAG.POST_NO IS '포스터번호';

COMMENT ON COLUMN TAG.TAG_NO IS '태그번호';

COMMENT ON COLUMN TAG.TAG_CONTENT IS '태그내용';

COMMENT ON TABLE TAG IS '태그';


CREATE TABLE SNS_COMMENT
(
    MEMBER_ID    character varying(30) NOT NULL,
    POST_NO    integer NOT NULL,
    SNS_COMMENT_NO    SERIAL not NULL,
    SNS_COMMENT_CON    character varying(1000) NOT NULL,
    SNS_COMMENT_DATE    timestamp without time zone NOT NULL,
    SNS_COMMENT_SEQ    integer NOT NULL,
    SNS_COMMENT_CLASS    integer NOT NULL,
    SNS_COMMENT_GROUP    integer
);

COMMENT ON COLUMN SNS_COMMENT.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN SNS_COMMENT.POST_NO IS '포스터번호';

COMMENT ON COLUMN SNS_COMMENT.SNS_COMMENT_NO IS 'SNS댓글번호';

COMMENT ON COLUMN SNS_COMMENT.SNS_COMMENT_CON IS 'SNS댓글내용';

COMMENT ON COLUMN SNS_COMMENT.SNS_COMMENT_DATE IS 'SNS댓글날짜';

COMMENT ON COLUMN SNS_COMMENT.SNS_COMMENT_SEQ IS 'SNS댓글순서';

COMMENT ON COLUMN SNS_COMMENT.SNS_COMMENT_CLASS IS 'SNS댓글계층';

COMMENT ON COLUMN SNS_COMMENT.SNS_COMMENT_GROUP IS 'SNS댓글그룹';

COMMENT ON TABLE SNS_COMMENT IS 'SNS댓글';

CREATE UNIQUE INDEX SNS_COMMENT_PK ON SNS_COMMENT
( MEMBER_ID,POST_NO,SNS_COMMENT_NO );

ALTER TABLE SNS_COMMENT
 ADD CONSTRAINT SNS_COMMENT_PK PRIMARY KEY 
 USING INDEX SNS_COMMENT_PK;

COMMENT ON COLUMN SNS_COMMENT.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN SNS_COMMENT.POST_NO IS '포스터번호';

COMMENT ON COLUMN SNS_COMMENT.SNS_COMMENT_NO IS 'SNS댓글번호';

COMMENT ON COLUMN SNS_COMMENT.SNS_COMMENT_CON IS 'SNS댓글내용';

COMMENT ON COLUMN SNS_COMMENT.SNS_COMMENT_DATE IS 'SNS댓글날짜';

COMMENT ON COLUMN SNS_COMMENT.SNS_COMMENT_SEQ IS 'SNS댓글순서';

COMMENT ON COLUMN SNS_COMMENT.SNS_COMMENT_CLASS IS 'SNS댓글계층';

COMMENT ON COLUMN SNS_COMMENT.SNS_COMMENT_GROUP IS 'SNS댓글그룹';

COMMENT ON TABLE SNS_COMMENT IS 'SNS댓글';


CREATE TABLE SNS_HEART
(
    MEMBER_ID    character varying(30) NOT NULL,
    POST_NO    integer NOT NULL,
    SNS_HEART_BOOL    boolean NOT NULL,
    SNS_HEART_NO    SERIAL not NULL
);

COMMENT ON COLUMN SNS_HEART.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN SNS_HEART.POST_NO IS '포스터번호';

COMMENT ON COLUMN SNS_HEART.SNS_HEART_BOOL IS 'SNS좋아요여부';

COMMENT ON COLUMN SNS_HEART.SNS_HEART_NO IS 'SNS좋아요번호';

COMMENT ON TABLE SNS_HEART IS 'SNS좋아요';

CREATE UNIQUE INDEX SNS_HEART_PK ON SNS_HEART
( MEMBER_ID,POST_NO,SNS_HEART_NO );

ALTER TABLE SNS_HEART
 ADD CONSTRAINT SNS_HEART_PK PRIMARY KEY 
 USING INDEX SNS_HEART_PK;

COMMENT ON COLUMN SNS_HEART.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN SNS_HEART.POST_NO IS '포스터번호';

COMMENT ON COLUMN SNS_HEART.SNS_HEART_BOOL IS 'SNS좋아요여부';

COMMENT ON COLUMN SNS_HEART.SNS_HEART_NO IS 'SNS좋아요번호';

COMMENT ON TABLE SNS_HEART IS 'SNS좋아요';


CREATE TABLE POST
(
    MEMBER_ID    character varying(30) NOT NULL,
    POST_NO    SERIAL not NULL,
    POST_CONTENT    character varying(1000) NOT NULL,
    POST_DATE    timestamp without time zone NOT NULL,
    POST_TYPE    character(1) NOT NULL
);

COMMENT ON COLUMN POST.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN POST.POST_NO IS '포스터번호';

COMMENT ON COLUMN POST.POST_CONTENT IS '포스트내용';

COMMENT ON COLUMN POST.POST_DATE IS '포스트등록일';

COMMENT ON COLUMN POST.POST_TYPE IS '포스트타입';

COMMENT ON TABLE POST IS 'SNS포스터';

CREATE UNIQUE INDEX POST_PK ON POST
( POST_NO );

ALTER TABLE POST
 ADD CONSTRAINT POST_PK PRIMARY KEY 
 USING INDEX POST_PK;

COMMENT ON COLUMN POST.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN POST.POST_NO IS '포스터번호';

COMMENT ON COLUMN POST.POST_CONTENT IS '포스트내용';

COMMENT ON COLUMN POST.POST_DATE IS '포스트등록일';

COMMENT ON COLUMN POST.POST_TYPE IS '포스트타입';

COMMENT ON TABLE POST IS 'SNS포스터';


CREATE TABLE FOLLOW
(
    MEMBER_ID    character varying(30) NOT NULL,
    FOLLOW_NO    SERIAL not NULL,
    FOLLOWER    character varying(30) NOT NULL,
    FOLLOWING    character varying(30) NOT NULL
);

COMMENT ON COLUMN FOLLOW.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN FOLLOW.FOLLOW_NO IS '팔로우번호';

COMMENT ON COLUMN FOLLOW.FOLLOWER IS '팔로워';

COMMENT ON COLUMN FOLLOW.FOLLOWING IS '팔로잉';

COMMENT ON TABLE FOLLOW IS '팔로우';

CREATE UNIQUE INDEX FOLLOW_PK ON FOLLOW
( MEMBER_ID,FOLLOW_NO );

ALTER TABLE FOLLOW
 ADD CONSTRAINT FOLLOW_PK PRIMARY KEY 
 USING INDEX FOLLOW_PK;

COMMENT ON COLUMN FOLLOW.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN FOLLOW.FOLLOW_NO IS '팔로우번호';

COMMENT ON COLUMN FOLLOW.FOLLOWER IS '팔로워';

COMMENT ON COLUMN FOLLOW.FOLLOWING IS '팔로잉';

COMMENT ON TABLE FOLLOW IS '팔로우';


CREATE TABLE COMMENT
(
    BOARD_NO    integer NOT NULL,
    COMMENT_NO    SERIAL not NULL,
    COMMENT_CON    character varying(500) NOT NULL,
    COMMENT_SEQ    integer NOT NULL,
    COMMENT_CLASS    integer NOT NULL,
    COMMENT_GROUP    integer NOT NULL,
    COMMENT_DATE    timestamp without time zone NOT NULL
);

COMMENT ON COLUMN COMMENT.BOARD_NO IS '게시글번호';

COMMENT ON COLUMN COMMENT.COMMENT_NO IS '댓글번호';

COMMENT ON COLUMN COMMENT.COMMENT_CON IS '댓글내용';

COMMENT ON COLUMN COMMENT.COMMENT_SEQ IS '댓글순서';

COMMENT ON COLUMN COMMENT.COMMENT_CLASS IS '댓글계층';

COMMENT ON COLUMN COMMENT.COMMENT_GROUP IS '댓글그룹';

COMMENT ON COLUMN COMMENT.COMMENT_DATE IS '댓글작성일';

COMMENT ON TABLE COMMENT IS '댓글';

CREATE UNIQUE INDEX COMMENT_PK ON COMMENT
( BOARD_NO,COMMENT_NO );

ALTER TABLE COMMENT
 ADD CONSTRAINT COMMENT_PK PRIMARY KEY 
 USING INDEX COMMENT_PK;

COMMENT ON COLUMN COMMENT.BOARD_NO IS '게시글번호';

COMMENT ON COLUMN COMMENT.COMMENT_NO IS '댓글번호';

COMMENT ON COLUMN COMMENT.COMMENT_CON IS '댓글내용';

COMMENT ON COLUMN COMMENT.COMMENT_SEQ IS '댓글순서';

COMMENT ON COLUMN COMMENT.COMMENT_CLASS IS '댓글계층';

COMMENT ON COLUMN COMMENT.COMMENT_GROUP IS '댓글그룹';

COMMENT ON COLUMN COMMENT.COMMENT_DATE IS '댓글작성일';

COMMENT ON TABLE COMMENT IS '댓글';


CREATE TABLE BOARD_IMG
(
    BOARD_NO    integer NOT NULL,
    BOARD_IMG_NO    SERIAL not NULL,
    BOARD_IMG_SEQ    integer NOT NULL,
    BOARD_IMG_IMG    character varying(200) NOT NULL,
    BOARD_IMG_UUID    character varying(100) NOT NULL
);

COMMENT ON COLUMN BOARD_IMG.BOARD_NO IS '게시글번호';

COMMENT ON COLUMN BOARD_IMG.BOARD_IMG_NO IS '게시글 이미지 번호';

COMMENT ON COLUMN BOARD_IMG.BOARD_IMG_SEQ IS '게시글 이미지 순서';

COMMENT ON COLUMN BOARD_IMG.BOARD_IMG_IMG IS '게시글 이미지 내용';

COMMENT ON COLUMN BOARD_IMG.BOARD_IMG_UUID IS '게시글 이미지 중복방';

COMMENT ON TABLE BOARD_IMG IS '게시물 이미지';

CREATE UNIQUE INDEX BOARD_IMG_PK ON BOARD_IMG
( BOARD_NO,BOARD_IMG_NO );

ALTER TABLE BOARD_IMG
 ADD CONSTRAINT BOARD_IMG_PK PRIMARY KEY 
 USING INDEX BOARD_IMG_PK;

COMMENT ON COLUMN BOARD_IMG.BOARD_NO IS '게시글번호';

COMMENT ON COLUMN BOARD_IMG.BOARD_IMG_NO IS '게시글 이미지 번호';

COMMENT ON COLUMN BOARD_IMG.BOARD_IMG_SEQ IS '게시글 이미지 순서';

COMMENT ON COLUMN BOARD_IMG.BOARD_IMG_IMG IS '게시글 이미지 내용';

COMMENT ON COLUMN BOARD_IMG.BOARD_IMG_UUID IS '게시글 이미지 중복방';

COMMENT ON TABLE BOARD_IMG IS '게시물 이미지';


CREATE TABLE HEART
(
    BOARD_NO    integer NOT NULL,
    MEMBER_ID    character varying(30) NOT NULL,
    HEART_BOOL    boolean NOT NULL,
    HEART_NO    SERIAL not NULL
);

COMMENT ON COLUMN HEART.BOARD_NO IS '게시글번호';

COMMENT ON COLUMN HEART.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN HEART.HEART_BOOL IS '좋아요 여부';

COMMENT ON COLUMN HEART.HEART_NO IS '좋아요 번호';

COMMENT ON TABLE HEART IS '좋아요';

CREATE UNIQUE INDEX HEART_PK ON HEART
( BOARD_NO,MEMBER_ID,HEART_NO );

ALTER TABLE HEART
 ADD CONSTRAINT HEART_PK PRIMARY KEY 
 USING INDEX HEART_PK;

COMMENT ON COLUMN HEART.BOARD_NO IS '게시글번호';

COMMENT ON COLUMN HEART.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN HEART.HEART_BOOL IS '좋아요 여부';

COMMENT ON COLUMN HEART.HEART_NO IS '좋아요 번호';

COMMENT ON TABLE HEART IS '좋아요';


CREATE TABLE BOARD
(
    MEMBER_ID    character varying(30) NOT NULL,
    BOARD_NO    SERIAL not NULL,
    BOARD_TITLE    character varying(50) NOT NULL,
    BOARD_BOARDER    character varying(20) NOT NULL,
    BOARD_DATE    timestamp without time zone NOT NULL,
    BOARD_CON    character varying(5000) NOT NULL,
    BOARD_SECREET    boolean NOT NULL,
    BOARD_TYPE    character(1) NOT NULL,
    BOARD_SEQ    integer NOT NULL,
    BOARD_VIEWS    integer NOT NULL,
    BOARD_KIND    character(1) NOT NULL
);

COMMENT ON COLUMN BOARD.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글번호';

COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';

COMMENT ON COLUMN BOARD.BOARD_BOARDER IS '작성자';

COMMENT ON COLUMN BOARD.BOARD_DATE IS '게시글작성일';

COMMENT ON COLUMN BOARD.BOARD_CON IS '게시글내용';

COMMENT ON COLUMN BOARD.BOARD_SECREET IS '비밀글여부';

COMMENT ON COLUMN BOARD.BOARD_TYPE IS '게시글타입';

COMMENT ON COLUMN BOARD.BOARD_SEQ IS '글순서';

COMMENT ON COLUMN BOARD.BOARD_VIEWS IS '조회수';

COMMENT ON COLUMN BOARD.BOARD_KIND IS '게시글종류';

COMMENT ON TABLE BOARD IS '게시판';

CREATE UNIQUE INDEX BOARD_PK ON BOARD
( BOARD_NO );

ALTER TABLE BOARD
 ADD CONSTRAINT BOARD_PK PRIMARY KEY 
 USING INDEX BOARD_PK;

COMMENT ON COLUMN BOARD.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글번호';

COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';

COMMENT ON COLUMN BOARD.BOARD_BOARDER IS '작성자';

COMMENT ON COLUMN BOARD.BOARD_DATE IS '게시글작성일';

COMMENT ON COLUMN BOARD.BOARD_CON IS '게시글내용';

COMMENT ON COLUMN BOARD.BOARD_SECREET IS '비밀글여부';

COMMENT ON COLUMN BOARD.BOARD_TYPE IS '게시글타입';

COMMENT ON COLUMN BOARD.BOARD_SEQ IS '글순서';

COMMENT ON COLUMN BOARD.BOARD_VIEWS IS '조회수';

COMMENT ON COLUMN BOARD.BOARD_KIND IS '게시글종류';

COMMENT ON TABLE BOARD IS '게시판';


CREATE TABLE MEM_INFO
(
    MEMBER_ID    character varying(30) NOT NULL,
    MEM_INFO_NO    SERIAL not NULL,
    MEM_INFO_GENDER    character(1),
    MEM_INFO_BIRTH    date,
    MEM_INFO_BANK    character varying(20),
    MEM_INFO_ACCOUNT    integer,
    MEM_INFO_RECI    character varying(20)
);

COMMENT ON COLUMN MEM_INFO.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN MEM_INFO.MEM_INFO_NO IS '추가정보번호';

COMMENT ON COLUMN MEM_INFO.MEM_INFO_GENDER IS '성별';

COMMENT ON COLUMN MEM_INFO.MEM_INFO_BIRTH IS '생일';

COMMENT ON COLUMN MEM_INFO.MEM_INFO_BANK IS '환불은행';

COMMENT ON COLUMN MEM_INFO.MEM_INFO_ACCOUNT IS '환불계좌';

COMMENT ON COLUMN MEM_INFO.MEM_INFO_RECI IS '환불수령자';

COMMENT ON TABLE MEM_INFO IS '추가정보';

CREATE UNIQUE INDEX MEM_INFO_PK ON MEM_INFO
( MEMBER_ID,MEM_INFO_NO );

ALTER TABLE MEM_INFO
 ADD CONSTRAINT MEM_INFO_PK PRIMARY KEY 
 USING INDEX MEM_INFO_PK;

COMMENT ON COLUMN MEM_INFO.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN MEM_INFO.MEM_INFO_NO IS '추가정보번호';

COMMENT ON COLUMN MEM_INFO.MEM_INFO_GENDER IS '성별';

COMMENT ON COLUMN MEM_INFO.MEM_INFO_BIRTH IS '생일';

COMMENT ON COLUMN MEM_INFO.MEM_INFO_BANK IS '환불은행';

COMMENT ON COLUMN MEM_INFO.MEM_INFO_ACCOUNT IS '환불계좌';

COMMENT ON COLUMN MEM_INFO.MEM_INFO_RECI IS '환불수령자';

COMMENT ON TABLE MEM_INFO IS '추가정보';


CREATE TABLE PRDT_OPTION
(
    PRODUCT_NO    integer NOT NULL,
    PRDT_OPTION_NO    SERIAL not NULL,
    PRDT_OPTION_SIZE    character varying(10) NOT NULL,
    PRDT_OPTION_STOCK    integer NOT NULL
);

COMMENT ON COLUMN PRDT_OPTION.PRODUCT_NO IS '상품번호';

COMMENT ON COLUMN PRDT_OPTION.PRDT_OPTION_NO IS '상품옵션번호';

COMMENT ON COLUMN PRDT_OPTION.PRDT_OPTION_SIZE IS '사이즈';

COMMENT ON COLUMN PRDT_OPTION.PRDT_OPTION_STOCK IS '재고량';

COMMENT ON TABLE PRDT_OPTION IS '상품옵션';

CREATE UNIQUE INDEX PRDT_OPTION_PK ON PRDT_OPTION
( PRDT_OPTION_NO );

ALTER TABLE PRDT_OPTION
 ADD CONSTRAINT PRDT_OPTION_PK PRIMARY KEY 
 USING INDEX PRDT_OPTION_PK;

COMMENT ON COLUMN PRDT_OPTION.PRODUCT_NO IS '상품번호';

COMMENT ON COLUMN PRDT_OPTION.PRDT_OPTION_NO IS '상품옵션번호';

COMMENT ON COLUMN PRDT_OPTION.PRDT_OPTION_SIZE IS '사이즈';

COMMENT ON COLUMN PRDT_OPTION.PRDT_OPTION_STOCK IS '재고량';

COMMENT ON TABLE PRDT_OPTION IS '상품옵션';


CREATE TABLE SELLER
(
    SELLER_NO    SERIAL not NULL,
    SELLER_NAME    character varying(30) NOT NULL,
    SELLER_TYPE    character(1) NOT NULL,
    SELLER_ADDR    character varying(100) NOT NULL,
    SELLER_ADDR2    character varying(100) NOT NULL,
    SELLER_ZIP    character varying(10) NOT NULL,
    SELLER_NUMBER    integer NOT NULL,
    MEMBER_ID    character varying(30) NOT NULL
);

COMMENT ON COLUMN SELLER.SELLER_NO IS '사업자번호';

COMMENT ON COLUMN SELLER.SELLER_NAME IS '회사명';

COMMENT ON COLUMN SELLER.SELLER_TYPE IS '판매자격';

COMMENT ON COLUMN SELLER.SELLER_ADDR IS '회사주소';

COMMENT ON COLUMN SELLER.SELLER_ADDR2 IS '회사상세주소';

COMMENT ON COLUMN SELLER.SELLER_ZIP IS '회사우편번호';

COMMENT ON COLUMN SELLER.SELLER_NUMBER IS '회사번호';

COMMENT ON COLUMN SELLER.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON TABLE SELLER IS '판매자';

CREATE UNIQUE INDEX SELLER_PK ON SELLER
( SELLER_NO );

ALTER TABLE SELLER
 ADD CONSTRAINT SELLER_PK PRIMARY KEY 
 USING INDEX SELLER_PK;

COMMENT ON COLUMN SELLER.SELLER_NO IS '사업자번호';

COMMENT ON COLUMN SELLER.SELLER_NAME IS '회사명';

COMMENT ON COLUMN SELLER.SELLER_TYPE IS '판매자격';

COMMENT ON COLUMN SELLER.SELLER_ADDR IS '회사주소';

COMMENT ON COLUMN SELLER.SELLER_ADDR2 IS '회사상세주소';

COMMENT ON COLUMN SELLER.SELLER_ZIP IS '회사우편번호';

COMMENT ON COLUMN SELLER.SELLER_NUMBER IS '회사번호';

COMMENT ON COLUMN SELLER.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON TABLE SELLER IS '판매자';


CREATE TABLE PRODUCT
(
    SELLER_NO    integer NOT NULL,
    PRODUCT_NO    SERIAL not NULL,
    PRODUCT_KIND    character(1) NOT NULL,
    PRODUCT_PRICE    integer NOT NULL,
    PRODUCT_DATE    timestamp without time zone NOT NULL,
    PRODUCT_NAME    character varying(500) NOT NULL
);

COMMENT ON COLUMN PRODUCT.SELLER_NO IS '사업자번호';

COMMENT ON COLUMN PRODUCT.PRODUCT_NO IS '상품번호';

COMMENT ON COLUMN PRODUCT.PRODUCT_KIND IS '상품종류';

COMMENT ON COLUMN PRODUCT.PRODUCT_PRICE IS '상품가격';

COMMENT ON COLUMN PRODUCT.PRODUCT_DATE IS '상품등록일';

COMMENT ON COLUMN PRODUCT.PRODUCT_NAME IS '상품이름';

COMMENT ON TABLE PRODUCT IS '상품';

CREATE UNIQUE INDEX PRODUCT_PK ON PRODUCT
( PRODUCT_NO );

ALTER TABLE PRODUCT
 ADD CONSTRAINT PRODUCT_PK PRIMARY KEY 
 USING INDEX PRODUCT_PK;

COMMENT ON COLUMN PRODUCT.SELLER_NO IS '사업자번호';

COMMENT ON COLUMN PRODUCT.PRODUCT_NO IS '상품번호';

COMMENT ON COLUMN PRODUCT.PRODUCT_KIND IS '상품종류';

COMMENT ON COLUMN PRODUCT.PRODUCT_PRICE IS '상품가격';

COMMENT ON COLUMN PRODUCT.PRODUCT_DATE IS '상품등록일';

COMMENT ON COLUMN PRODUCT.PRODUCT_NAME IS '상품이름';

COMMENT ON TABLE PRODUCT IS '상품';


CREATE TABLE PRDT_ORDER
(
    PRDT_ORDER_NO    SERIAL not NULL,
    PRODUCT_NO    integer NOT NULL,
    MEMBER_ID    character varying(30) NOT NULL,
    PRDT_ORDER_QUAN    integer NOT NULL,
    PRDT_ORDER_DATE    boolean NOT NULL,
    PRDT_ORDER_TYPE    character(1) NOT NULL,
    PRDT_ORDER_PHONE    integer NOT NULL,
    PRDT_ORDER_ADDR    character varying(100) NOT NULL,
    PRDT_ORDER_ADDR2    character varying(100) NOT NULL,
    PRDT_ORDER_PERSON    character varying(50) NOT NULL,
    PRDT_ORDER_TYPE1    character(1) NOT NULL
);

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_NO IS '주문번호';

COMMENT ON COLUMN PRDT_ORDER.PRODUCT_NO IS '상품번호';

COMMENT ON COLUMN PRDT_ORDER.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_QUAN IS '주문수량';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_DATE IS '주문일자';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_TYPE IS '결제수단';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_PHONE IS '수령자 폰번호';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_ADDR IS '수령지주소';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_ADDR2 IS '수령지상세주소';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_PERSON IS '수령인';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_TYPE1 IS '상품타입';

COMMENT ON TABLE PRDT_ORDER IS '주문';

CREATE UNIQUE INDEX PRDT_ORDER_PK ON PRDT_ORDER
( PRODUCT_NO,MEMBER_ID,PRDT_ORDER_NO );

ALTER TABLE PRDT_ORDER
 ADD CONSTRAINT PRDT_ORDER_PK PRIMARY KEY 
 USING INDEX PRDT_ORDER_PK;

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_NO IS '주문번호';

COMMENT ON COLUMN PRDT_ORDER.PRODUCT_NO IS '상품번호';

COMMENT ON COLUMN PRDT_ORDER.MEMBER_ID IS '아이디(E-Mail)';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_QUAN IS '주문수량';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_DATE IS '주문일자';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_TYPE IS '결제수단';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_PHONE IS '수령자 폰번호';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_ADDR IS '수령지주소';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_ADDR2 IS '수령지상세주소';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_PERSON IS '수령인';

COMMENT ON COLUMN PRDT_ORDER.PRDT_ORDER_TYPE1 IS '상품타입';

COMMENT ON TABLE PRDT_ORDER IS '주문';

CREATE TABLE PRDT_IMG
(
    PRODUCT_NO    integer NOT NULL,
    PRDT_IMG_NO    SERIAL not NULL,
    PRDT_IMG_SEQ    integer NOT NULL,
    PRDT_IMG_NAME    character varying(200) NOT NULL,
    PRDT_IMG_UUID    character varying(100) NOT NULL
);

COMMENT ON COLUMN PRDT_IMG.PRODUCT_NO IS '상품번호';

COMMENT ON COLUMN PRDT_IMG.PRDT_IMG_NO IS '상품이미지번호';

COMMENT ON COLUMN PRDT_IMG.PRDT_IMG_SEQ IS '상품이미지순서';

COMMENT ON COLUMN PRDT_IMG.PRDT_IMG_NAME IS '상품이미지';

COMMENT ON COLUMN PRDT_IMG.PRDT_IMG_UUID IS '중복방지';

COMMENT ON TABLE PRDT_IMG IS '상품이미지';

CREATE UNIQUE INDEX PRDT_IMG_PK ON PRDT_IMG
( PRODUCT_NO,PRDT_IMG_NO );

ALTER TABLE PRDT_IMG
 ADD CONSTRAINT PRDT_IMG_PK PRIMARY KEY 
 USING INDEX PRDT_IMG_PK;

COMMENT ON COLUMN PRDT_IMG.PRODUCT_NO IS '상품번호';

COMMENT ON COLUMN PRDT_IMG.PRDT_IMG_NO IS '상품이미지번호';

COMMENT ON COLUMN PRDT_IMG.PRDT_IMG_SEQ IS '상품이미지순서';

COMMENT ON COLUMN PRDT_IMG.PRDT_IMG_NAME IS '상품이미지';

COMMENT ON COLUMN PRDT_IMG.PRDT_IMG_UUID IS '중복방지';

COMMENT ON TABLE PRDT_IMG IS '상품이미지';


